<a href="https://colab.research.google.com/github/Gabriel-Amorim-dev/Alura/blob/main/Aula1_DataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 1

In [1]:
import pandas as pd

leitura do arquivo CSV

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

# **Informações iniciais acerca do dataset importado.**

---

### *Vantagens:*

* Nos ajuda a ter uma **visão inicial** acerca da data importada  
* Ajuda a **planejar o rumo de ação** com as informações dos dados fornecidos

In [3]:
df.info()
#COMPREENSÃO DA INFO DO MEU DATASET

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB


# **Describe**

A função `.describe()` fornece dados estatísticos acerca do nosso arquivo, mas também pode ser usada para extração de colunas específicas (quantidade de valores não nulos, máximo, mínimo, padrão).

---

### Exemplo:

```python
# df['Cargo'].describe()
````

Esse comando fornece os dados estatísticos possíveis de obter na coluna de Cargos.
Levando em consideração que a coluna não é do tipo numérico, ela oferece informações não numéricas (Moda, Frequência da Moda, Número de não nulos).

---

### *Vantagens:*

1. Útil para a extração de dados extremos
2. Entender a dispersão e concentração numérica dos valores

In [4]:
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000


# **Shape**

A função `.shape` não é um método, mas sim um atributo do DataFrame que retorna uma tupla com duas informações:  
→ número de linhas (registros) e número de colunas (variáveis) no seu DataFrame.

---

### Exemplo:

```python
df.shape
````

Esse comando retorna algo como:

```
(1000, 10)
```

Isso significa que o DataFrame possui **1000 linhas** e **10 colunas**.

---

### *Vantagens:*

1. Ideal para verificar a dimensão do dataset
2. Útil para saber se há dados suficientes para análise
3. Pode ser usado em etapas de validação, como antes e depois de tratamentos de dados (por exemplo, remoção de nulos ou duplicados)

In [5]:
linhas, colunas = df.shape[0], df.shape[1]
print(f'O programa tem, {linhas} linhas')
print(f'O programa tem, {colunas} colunas')

O programa tem, 133349 linhas
O programa tem, 11 colunas

# **Dicionário**

A função 'dicionário' foi definida para gerar um bloco de traduções de termos e siglas do documento original que poderiam dificultar a leitura agradável dos valores documentados nos dados do arquivo.

Assim, a tradução ou adaptação de certos aspectos contribui para a extração e manipulação eficaz de dados.

In [6]:
def dicionario():
      contrato = {
                'PT': 'Meio Período',
                'FT': 'Integral',
                'CT': 'Contrato',
                'FL': 'Freelancer'
      }
      nivel = {
                'SE': 'Senior',
                'MI': 'Pleno',
                'EN': 'Junior',
                'EX': 'Executivo'
      }
      tamanho = {
                'S': 'Pequeno',
                'M': 'Médio',
                'L': 'Grande'
      }
      moeda = {
                'USD': 'Dólar americano',
                'EUR': 'Euro',
                'GBP': 'Libra esterlina',

      }
      loc_empresa = {
          'US': 'Estados Unidos',
          'AU': 'Austrália',
          'CA': 'Canadá',
          'JP': 'Japão',
          'GB': 'Reino Unido',
          'MX': 'México',
          'NL': 'Países Baixos',
          'ES': 'Espanha',
          'FR': 'França',
          'MT': 'Malta',
          'LT': 'Lituânia',
          'PH': 'Filipinas',
          'NZ': 'Nova Zelândia',
          'DE': 'Alemanha',
          'LV': 'Letônia',
          'IE': 'Irlanda',
          'MK': 'Macedônia do Norte',
          'AT': 'Áustria',
          'PL': 'Polônia',
          'SK': 'Eslováquia',
          'BR': 'Brasil',
          'SI': 'Eslovênia',
          'FI': 'Finlândia',
          'HK': 'Hong Kong',
          'LS': 'Lesoto',
          'IN': 'Índia',
          'JM': 'Jamaica',
          'CH': 'Suíça',
          'BE': 'Bélgica',
          'PE': 'Peru',
          'SG': 'Singapura',
          'PT': 'Portugal',
          'IT': 'Itália',
          'HU': 'Hungria',
          'RO': 'Romênia',
          'AR': 'Argentina',
          'ZA': 'África do Sul',
          'PA': 'Panamá',
          'EE': 'Estônia',
          'LU': 'Luxemburgo',
          'DZ': 'Argélia',
          'EG': 'Egito',
          'CL': 'Chile',
          'GR': 'Grécia',
          'KE': 'Quênia',
          'CD': 'República Democrática do Congo',
          'SE': 'Suécia',
          'KR': 'Coreia do Sul',
          'TW': 'Taiwan',
          'NO': 'Noruega',
          'CZ': 'Tchéquia',
          'TR': 'Turquia',
          'CY': 'Chipre',
          'CO': 'Colômbia',
          'DK': 'Dinamarca',
          'AE': 'Emirados Árabes Unidos',
          'BG': 'Bulgária',
          'ID': 'Indonésia',
          'JO': 'Jordânia',
          'RS': 'Sérvia',
          'UA': 'Ucrânia',
          'PR': 'Porto Rico',
          'SV': 'El Salvador',
          'EC': 'Equador',
          'DO': 'República Dominicana',
          'MY': 'Malásia',
          'XK': 'Kosovo',
          'CR': 'Costa Rica',
          'ZM': 'Zâmbia',
          'AM': 'Armênia',
          'IL': 'Israel',
          'LB': 'Líbano',
          'NG': 'Nigéria',
          'HR': 'Croácia',
          'PK': 'Paquistão',
          'HN': 'Honduras',
          'VE': 'Venezuela',
          'AS': 'Samoa Americana',
          'SA': 'Arábia Saudita',
          'OM': 'Omã',
          'BA': 'Bósnia e Herzegovina',
          'VN': 'Vietnã',
          'GI': 'Gibraltar',
          'MU': 'Maurício',
          'RU': 'Rússia',
          'QA': 'Catar',
          'GH': 'Gana',
          'AD': 'Andorra',
          'CF': 'República Centro-Africana',
          'TH': 'Thailand',
          'IR': 'Iran',
          'BS': 'Bahamas',
          'IQ': 'Iraque',
          'CN': 'China',
          'MD': 'Moldova'
      }

      return contrato, nivel, tamanho, moeda, loc_empresa

contrato_map, nivel_map, tamanho_map, moeda_map, loc_empresa_map = dicionario()

df['employment_type'] = df['employment_type'].replace(contrato_map)

df['experience_level'] = df['experience_level'].replace(nivel_map)

df['salary_currency'] = df['salary_currency'].replace(moeda_map)

df['company_location'] = df['company_location'].replace(loc_empresa_map)

df['company_size'] = df['company_size'].replace(tamanho_map)

# **Rename**

---

A função `.rename()` tem como principal função o renomear colunas ou índices (linhas) de um DataFrame sem precisar necessariamente recriá-lo.

É muito útil para a limpeza dos dados, especialmente quando os nomes estão em algum idioma não falado pelo analista ou por qualquer responsável pela informação.

Nesse Dashboard, substitui termos em inglês que não possuíam uma visibilidade amigável por termos simples em português.

O parâmetro `inplace=True` indica que a modificação será feita no DataFrame original, renomeando-a no próprio objeto.

In [7]:
df.rename(columns={
    'work_year': 'Ano',
    'experience_level': 'Nível',
    'employment_type': 'Contrato',
    'job_title': 'Cargo',
    'salary': 'Salário (local)',
    'salary_currency': 'Moeda',
    'salary_in_usd': 'Salário (USD)',
    'employee_residence': 'Residência',
    'remote_ratio': 'Remoto (%)',
    'company_location': 'Local Empresa',
    'company_size': 'Tamanho'
}, inplace=True)

# **Organização por Tipo de Dados**

---

Esse bloco de código tem como objetivo organizar e exibir as colunas do DataFrame `df` agrupadas por tipo de dado, o que facilita a leitura e a análise.

### 🔍 O que o código faz:

```python
types = df.dtypes
````

Retorna os tipos de dados de cada coluna do DataFrame (ex: `float64`, `int64`, `object`).

```python
# float_cols = types[types == 'float64'].index.tolist()
# int_cols = types[types == 'int64'].index.tolist()
# obj_cols = types[types == 'object'].index.tolist()
```

Cria 3 listas separadas com os nomes das colunas, agrupando por tipo:

```text
float_cols: colunas com números decimais (float64)

int_cols: colunas com números inteiros (int64)

obj_cols: colunas com textos ou categorias (object)
```

```python
columns_order = float_cols + int_cols + obj_cols
df = df[columns_order]
```

Reorganiza o DataFrame colocando as colunas em uma ordem lógica: primeiro floats, depois ints, por fim os objetos.

```python
df.head().style.set_properties(**{'text-align': 'center'}).set_table_styles(
    [dict(selector='th', props=[('text-align', 'center')])]
)
```

Formata a exibição da tabela para alinhar os dados e títulos ao centro.

```python
display(df.head(10))
```

Mostra os 10 primeiros registros já organizados e centralizados.

---

### *✅ Vantagens:*

* Torna a leitura do DataFrame mais limpa e estruturada
* Ajuda a identificar rapidamente quais tipos de dados estão presentes
* Facilita análises estatísticas e visuais ao agrupar colunas semelhantes
* Deixa a apresentação dos dados mais profissional e clara, especialmente em notebooks e dashboards

In [8]:
types = df.dtypes


float_cols = types[types == 'float64'].index.tolist()
int_cols = types[types == 'int64'].index.tolist()
obj_cols = types[types == 'object'].index.tolist()

columns_order = float_cols + int_cols + obj_cols
df = df[columns_order]

df.head().style.set_properties(**{'text-align': 'center'}).set_table_styles(
    [dict(selector='th', props=[('text-align', 'center')])]
)

display(df.head(10))

,Ano,Salário (local),Salário (USD),Remoto (%),Nível,Contrato,Cargo,Moeda,Residência,Local Empresa,Tamanho
0,2025.0,214000,214000,100,Senior,Integral,Solutions Engineer,Dólar americano,US,Estados Unidos,Médio
1,2025.0,136000,136000,100,Senior,Integral,Solutions Engineer,Dólar americano,US,Estados Unidos,Médio
2,2025.0,158800,158800,0,Pleno,Integral,Data Engineer,Dólar americano,AU,Austrália,Médio
3,2025.0,139200,139200,0,Pleno,Integral,Data Engineer,Dólar americano,AU,Austrália,Médio
4,2025.0,90000,90000,0,Junior,Integral,Data Engineer,Dólar americano,US,Estados Unidos,Médio
5,2025.0,80000,80000,0,Junior,Integral,Data Engineer,Dólar americano,US,Estados Unidos,Médio
6,2025.0,185000,185000,0,Senior,Integral,Data Scientist,Dólar americano,US,Estados Unidos,Médio
7,2025.0,148000,148000,0,Senior,Integral,Data Scientist,Dólar americano,US,Estados Unidos,Médio
8,2025.0,135000,135000,0,Pleno,Integral,Data Scientist,Dólar americano,CA,Canadá,Médio
9,2025.0,108000,108000,0,Pleno,Integral,Data Scientist,Dólar americano,CA,Canadá,Médio

**Operações Interativas em Colunas do DataFrame**



---



Esse código permite que o usuário escolha uma coluna do DataFrame para realizar diversas operações exploratórias simples, facilitando a análise de dados sem precisar digitar comandos manualmente.

🔍 O que o código faz:
```
print('Informações Disponíveis:')
print(df.columns.tolist())
info = input('Qual informação você quer saber? ')
```
Exibe as colunas disponíveis no DataFrame.

Recebe do usuário o nome da coluna que ele quer analisar.

```
def operations(coluna):
  print('\nEscolha a operação que deseja realizar:')
  print('1 - Ver primeiras linhas')
  print('2 - Ver últimas linhas')
  print('3 - Ver tipo de dado e nulos')
  print('4 - Ver estatísticas')
  print('5 - Ver quantos valores nulos')
  print('6 - Ver quantas duplicadas')
  print('7 - Ver quantos valores')
  ```
Define um menu com 7 opções de operações para explorar a coluna escolhida.
```
func = int(input('Digite o número da operação: '))
```
Recebe a operação que o usuário deseja executar.
```
match func:

  case 1:
    print(df[coluna].head())
  case 2:
    print(df[coluna].tail())
  case 3:
    print(f"Tipo de dado: {df[coluna].dtype}")
    print(f"Quantidade de nulos: {df[coluna].isnull().sum()}")
  case 4:
    print(df[coluna].describe())
  case 5:
    print(f"Valores nulos: {df[coluna].isnull().sum()}")
  case 6:
    print(f"Duplicadas: {df[coluna].duplicated().sum()}")
  case 7:
    print(f'Contagem de Valores: {df[coluna].value_counts()}')
  case _:
    print("Opção inválida.")
```
Executa a operação selecionada pelo usuário:

1: mostra as primeiras 5 linhas da coluna.

2: mostra as últimas 5 linhas da coluna.

3: mostra o tipo de dado da coluna e a quantidade de valores nulos.

4: mostra as estatísticas descritivas da coluna (média, quartis, etc.).

5: conta quantos valores nulos a coluna possui.

6: conta quantas linhas duplicadas a coluna possui.

7: mostra a contagem de valores únicos da coluna.

Caso o número seja inválido, avisa o usuário.

```
operations(info)
```
Chama a função operations passando a coluna escolhida para executar a operação.

*✅ Vantagens:*



---



Interface simples para explorar qualquer coluna rapidamente.

Facilita análise exploratória sem precisar lembrar de comandos Pandas.

Permite obter informações básicas, estatísticas e dados sobre qualidade da coluna (nulos e duplicados).

Pode ser ampliado com mais operações conforme a necessidade.

In [9]:
print('Informações Disponíveis:')
print(df.columns.tolist())
info = input('Qual informação você quer saber? ')

def operations(coluna):
  print('\nEscolha a operação que deseja realizar:')
  print('1 - Ver primeiras linhas')
  print('2 - Ver últimas linhas')
  print('3 - Ver tipo de dado e nulos')
  print('4 - Ver estatísticas')
  print('5 - Ver quantos valores nulos')
  print('6 - Ver quantas duplicadas')
  print('7 - Ver quantos valores')


  func = int(input('Digite o número da operação: '))

  match func:
    case 1:
      print(df[coluna].head())
    case 2:
      print(df[coluna].tail())
    case 3:
      print(f"Tipo de dado: {df[coluna].dtype}")
      print(f"Quantidade de nulos: {df[coluna].isnull().sum()}")
    case 4:
      print(df[coluna].describe())
    case 5:
      print(f"Valores nulos: {df[coluna].isnull().sum()}")
    case 6:
      print(f"Duplicadas: {df[coluna].duplicated().sum()}")
    case 7:
      print(f'Contagem de Valores: {df[coluna].value_counts()}')
    case _:
      print("Opção inválida.")

operations(info)

Informações Disponíveis:
['Ano', 'Salário (local)', 'Salário (USD)', 'Remoto (%)', 'Nível', 'Contrato', 'Cargo', 'Moeda', 'Residência', 'Local Empresa', 'Tamanho']
Qual informação você quer saber? Nível

Escolha a operação que deseja realizar:
1 - Ver primeiras linhas
2 - Ver últimas linhas
3 - Ver tipo de dado e nulos
4 - Ver estatísticas
5 - Ver quantos valores nulos
6 - Ver quantas duplicadas
7 - Ver quantos valores
Digite o número da operação: 3
Tipo de dado: object
Quantidade de nulos: 0



**Gráficos Interativos para Análise de Dados**

Esse código permite que o usuário escolha uma coluna categórica e uma coluna numérica do DataFrame para visualizar diferentes tipos de gráficos, facilitando a exploração visual dos dados.

---

### 🔍 O que o código faz:

```python
print('Informações Disponíveis:')
print(df.columns.tolist())
````

* Exibe as colunas disponíveis no DataFrame para ajudar o usuário a escolher.

```python
info_categoria = input('Qual coluna categórica você quer analisar? ')
info_valor = input('Qual valor numérico você quer visualizar (ex: salary_in_usd)? ')
```

* Solicita ao usuário o nome da coluna categórica (ex: cargo, país) e da coluna numérica (ex: salário).

```python
if info_categoria not in df.columns or info_valor not in df.columns:
    raise ValueError("Coluna não encontrada.")
```

* Verifica se as colunas existem no DataFrame.

```python
if not pd.api.types.is_numeric_dtype(df[info_valor]):
    raise TypeError("A variável inserida não é numérica!")
```

* Garante que a coluna numérica realmente contém valores numéricos.

```python
info_calc = df.groupby(info_categoria)[info_valor].mean().sort_values(ascending=False)
```

* Agrupa os dados pela categoria escolhida e calcula a média do valor numérico para cada grupo, ordenando do maior para o menor.

---

### 🎨 Menu de gráficos:

```python
print('\nEscolha o gráfico que deseja analisar:')
print('1 - Gráfico de Barras')
print('2 - Gráfico de Pizza (só para poucos itens)')
print('3 - Gráfico de Caixa (Boxplot)')
print('4 - Gráfico de Linhas')
print('5 - Scatterplot')
```

O usuário escolhe o gráfico que deseja visualizar.

---

### 🎯 O que cada gráfico faz:

| Opção | Gráfico                        | Descrição                                                                                              |
| ----- | ------------------------------ | ------------------------------------------------------------------------------------------------------ |
| 1     | **Gráfico de Barras**          | Compara a média da variável numérica para cada categoria, mostrando barras ordenadas.                  |
| 2     | **Gráfico de Pizza**           | Mostra a proporção das 10 maiores categorias, útil para poucas categorias.                             |
| 3     | **Gráfico de Caixa (Boxplot)** | Exibe a distribuição, quartis e possíveis outliers da variável numérica para cada categoria.           |
| 4     | **Gráfico de Linhas**          | Mostra a tendência da média da variável numérica ao longo das categorias (útil para séries temporais). |
| 5     | **Scatterplot**                | Mostra a dispersão dos dados individuais da variável numérica em relação às categorias.                |

---

### 🖥️ Como o código gera os gráficos:

* Cada opção chama a função específica do Matplotlib/Seaborn para desenhar o gráfico com as configurações de títulos, rótulos e tamanhos adequados.
* Gráficos são exibidos em janela de visualização ou notebook.
* O código trata entrada inválida de forma simples.

---

### *✅ Vantagens:*

* Permite uma exploração visual rápida e personalizada de dados.
* Facilita a identificação de padrões, tendências e anomalias.
* Pode ser usado em notebooks para análises interativas.
* Com poucos comandos, gera gráficos claros e informativos.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Mostra as colunas
print('Informações Disponíveis:')
print(df.columns.tolist())

try:
    info_categoria = input('Qual coluna categórica você quer analisar? ')
    info_valor = input('Qual valor numérico você quer visualizar (ex: Salário (USD)? ')

    # Verifica se as colunas existem
    if info_categoria not in df.columns or info_valor not in df.columns:
        raise ValueError("Coluna não encontrada.")

    # Verifica se a coluna de valor é numérica
    if not pd.api.types.is_numeric_dtype(df[info_valor]):
        raise TypeError("A variável inserida não é numérica!")

    # Agrupamento
    info_calc = df.groupby(info_categoria)[info_valor].mean().sort_values(ascending=False)

except Exception as e:
    print(f'Erro: {e}')
else:
    def graficos():
        print('\nEscolha o gráfico que deseja analisar:')
        print('1 - Gráfico de Barras')
        print('2 - Gráfico de Pizza (só para poucos itens)')
        print('3 - Gráfico de Caixa (Boxplot)')
        print('4 - Gráfico de Linhas')
        print('5 - Scatterplot')

        try:
            func = int(input('Digite o número da operação: '))
        except ValueError:
            print("Entrada inválida. Digite um número.")
            return

        match func:
            case 1:
                plt.figure(figsize=(10, 6))
                sns.barplot(x=info_calc.values, y=info_calc.index)
                plt.xlabel(f'Média de {info_valor}')
                plt.ylabel(info_categoria)
                plt.title(f'Média de {info_valor} por {info_categoria}')
                plt.tight_layout()
                plt.show()

            case 2:
                top10 = info_calc.head(10)
                plt.figure(figsize=(8, 8))
                plt.pie(top10, labels=top10.index, autopct='%1.1f%%')
                plt.title(f'Top 10 {info_categoria} por média de {info_valor}')
                plt.show()

            case 3:
                plt.figure(figsize=(10, 6))
                sns.boxplot(x=info_categoria, y=info_valor, data=df)
                plt.xticks(rotation=45)
                plt.title(f'Distribuição de {info_valor} por {info_categoria}')
                plt.tight_layout()
                plt.show()

            case 4:
                plt.figure(figsize=(12, 6))
                sns.lineplot(x=info_calc.index, y=info_calc.values, marker='o')
                plt.title(f'Tendência da média de {info_valor} por {info_categoria}')
                plt.ylabel(f'{info_valor}')
                plt.xlabel(info_categoria)
                plt.xticks(rotation=45)
                plt.tight_layout()
                plt.show()

            case 5:
                plt.figure(figsize=(10, 6))
                sns.scatterplot(data=df, x=info_categoria, y=info_valor)
                plt.title(f'Dispersão de {info_valor} por {info_categoria}')
                plt.xticks(rotation=45)
                plt.tight_layout()
                plt.show()

            case _:
                print("Opção inválida.")

    graficos()

Informações Disponíveis:
['Ano', 'Salário (local)', 'Salário (USD)', 'Remoto (%)', 'Nível', 'Contrato', 'Cargo', 'Moeda', 'Residência', 'Local Empresa', 'Tamanho']